### ISSUE TITLE
Plaats style rules op een logische plek

### ISSUE THREAD

**Issue by joostf** [vsheo/look-and-feel-styleguide#13]
https://github.com/vsheo/look-and-feel-corporate-identity/blob/c066ddd99d85779f476647807ad22b81aa2bb0d6/styles/style.css#L1-L19

Kunnen deze generieke element selectoren in de gezamenlijke stylesheet?

**Comment by vsheo** [comment]
We hebben deze elementen nu in de gezaamlijke stylesheet geplaatst.
