### ISSUE TITLE
Feedback op README

### ISSUE THREAD

**Issue by Karima002** [vsheo/look-and-feel-styleguide#3]
Kortere class naam geven bij `<figure>` 

`<figure>`  
`<code class="brand-primary brand-primary-veronica">#0091FF</code>`    
`<figcaption>Brand-kleur Veronica</figcaption>`  
`</figure>`

`brand-primary brand-primary-veronica` kan korter geschreven worden door `brand-primary veronica`. In de CSS kan je zowel `brand-primary-veronica` als `brand-primary` schrijven.

Deze feedback is geschreven door @mikiyas-hs @divaniNL @fatimahilali @Karima002

**Comment by vsheo** [comment]
We zullen in de class names het woordje brand weghalen.
brand en veronica is hetzelfde.

**Comment by julia-stevens** [comment]
**Commit:** [8dd8363](https://github.com/vsheo/look-and-feel-styleguide/commit/8dd8363a5168ca585bd8ebd5d1b876c4ce7174c6) 

De class names zijn aangepast: 
* `brand-primary` is nu `primary`
* `brand-primary-veronica` is nu `veronica-primary`

In HTML kan dit niet herschreven worden als `"brand-primary veronica"`, omdat Radio Veronica meerdere kleuren heeft en dit kan dus niet één class zijn. Het leek ons dus het overzichtelijkste om dit dezelfde naam te geven als de class die daarvoor staat, in dit geval dus: `veronica-primary`
