### ISSUE TITLE
Uitleg ReadMe iets duidelijker

### ISSUE THREAD

**Issue by saschavanvliet** [vsheo/look-and-feel-styleguide#4]
Jullie hebben een goede ReadMe geschreven waarbij jullie zelfs de gemaakte afspraken hebben gerapporteerd. Echter begrijpen wij sommige stukken uitleg niet zo goed. Misschien dat de uitleg van de code bijvoorbeeld iets uitgebreider beschreven kan worden. Nu staat het er redelijk beknopt. 

Met vriendelijke groet, Team Drop&Heal

**Comment by vsheo** [comment]
we zullen meer uitleg geven over hoe onze code gebruikt wordt in de readme

**Comment by julia-stevens** [comment]
**Commit**:  4a01c02

README aangepast en meer uitleg toegevoegd van hoe de code kan worden toegepast, met concrete voorbeelden en een korte uitleg, waarom er 2 classes worden gebruikt in HTML
