### ISSUE TITLE
Feedback op pixels door Redpers

### ISSUE THREAD

**Issue by Karima002** [vsheo/look-and-feel-styleguide#5]
Voor de font-size is het beter om em te gebruiken. Je kan een converter van px naar em gebruiken: https://pixelsconverter.com/px-to-em

Deze feedback is geschreven door @mikiyas-hs @fatimahilali @DivaniNL @karima002

**Comment by vsheo** [comment]
We zullen h2 tot h6 veranderen van px naar em.
h1 zullen we als px laten.
we zullen ook clamp toevoegen om het responsive te maken

**Comment by poormoa00** [comment]
5f9b14c2fb2523ee277a991ebdaf998e0d38fcef
