### ISSUE TITLE
Duidelijke benaming geven aan classes en custom properties

### ISSUE THREAD

**Issue by saschavanvliet** [vsheo/look-and-feel-styleguide#6]
Jullie hebben gebruikt gemaakt van classes en custom properties, maar het is ons soms niet helemaal duidelijk wat er precies bedoeld wordt met bepaalde naamgeving. Wat betekent bijvoorbeeld '100p'? Misschien is het ook een tip om bij de custom property 'text-primary' aan te geven dat het om een kleur gaat.

```
.background-neutral-100p {
    --background-neutral: #FFFFFF;
}

.text-primary-100p {
    --text-primary: #1E1E1E;
}
```

We snappen ook niet waarom er gebruikt wordt gemaakt van twee keer brand primary achter elkaar. Is hier een goede reden voor?
```
    <figure>
      <code class="brand-primary brand-primary-veronica">#0091FF</code>
      <figcaption>Brand-kleur Veronica</figcaption>
    </figure>
```

Groetjes team Drop&Heal!!!

**Comment by vsheo** [comment]
We zullen in onze readme beter uitleggen hoe en waarom we 2 classes gebruiken

**Comment by julia-stevens** [comment]
**Commit:** [8dd8363](https://github.com/vsheo/look-and-feel-styleguide/commit/8dd8363a5168ca585bd8ebd5d1b876c4ce7174c6)

1. 100p staat voor de radiozender 100%NL, aangezien je geen '%' kunt gebruiken, is dit aangegeven met een 'p'. Om het leesbaarder te maken hebben we '100' veranderd naar 'honderd', dus `100p` is nu `honderdp`

2. De class names zijn aangepast: 
* `brand-primary` is nu `primary`
* `brand-primary-veronica` is nu `veronica-primary`

3. In de [README]() staat een uitleg over hoe de twee classes toegepast kunnen worden. Hieronder een uitleg: 

Kort gezegd, in de `primary` class wordt bv. de achtergrond kleur bepaald met de variabele `--brand-primary`. Voor elk radiostation (Veronica, SLAM, 100%NL en Sublime) is een class gemaakt waarin er een achtergrond wordt meegegeven aan de `--brand-primary` variabele. Hiermee zorgen we ervoor dat we maar één moeten aangegeven dát een element een achtergrond kleur krijgt en kunnen we in HTML, door het toevoegen van een class (zoals `primary-veronica`), bepalen welke kleur dit moet zijn.
