### ISSUE TITLE
Jullie hebben geen duidelijke buttons

### ISSUE THREAD

**Issue by saschavanvliet** [vsheo/look-and-feel-styleguide#7]
Jullie hebben helaas geen hovers over de buttons gebruikt. Er komt alleen een underline tevoorschijn, maar het is geen link. Misschien kunnen jullie ervoor zorgen dat de volledige button naar voren komt.

Hoogachtend, team Drop&Heal

**Comment by vsheo** [comment]
we hebben nu style voor buttons en hover over een button.
